name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: TQTuyen/ci-cd-toolkit/.github/workflows/cd-deploy-cloud-run.yml@main
    with:
      service: iris
      image: asia-southeast1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/iris/iris:main
      region: asia-southeast1
      project-id: ${{ vars.GCP_PROJECT_ID }}
    secrets:
      wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
      service-account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    permissions:
      contents: read
      id-token: write
