name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: TQTuyen/ci-cd-toolkit/.github/workflows/cd-deploy-gce.yml@main
    with:
      image: asia-southeast1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/iris/iris:main
      container-name: iris
      deploy-path: /opt/sfinx/iris
    secrets:
      ssh-host: ${{ secrets.VM_HOST }}
      ssh-user: ${{ secrets.VM_USER }}
      ssh-key: ${{ secrets.VM_SSH_KEY }}
      env-file-content: ${{ secrets.ENV_PROD }}
